apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres  # O nome do app (ou pod) que você está usando para o PostgreSQL
  ports:
    - protocol: TCP
      port: 5432  # A porta do PostgreSQL
      targetPort: 5432  # A porta interna do pod
  type: LoadBalancer  # Expor o PostgreSQL com LoadBalancer
