apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 8080  # Porta interna do seu pod
      targetPort: 8080  # A porta que sua aplicação escuta
  type: LoadBalancer  # Isso vai permitir o acesso externo, se você estiver usando um cluster com suporte a LoadBalancer
